# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Android Testing"
  lane :test do
    gradle(task: "test")
  end


  desc "Push a new beta build to Firebase App Distribution"
  lane :beta do
    # gradle(task: "clean assembleRelease")
    # crashlytics
    gradle(
      task: 'assemble',
      build_type: 'Release'
    )

    # sh "your_script.sh"
    # You can also use other beta testing services here

    firebase_app_distribution(
      app: ENV["FIREBASE_ANDROID_APP"],
      firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
      release_notes: "Lots of amazing new features to test out!",
      groups: ENV["FIREBASE_ANDROID_GROUPS"]
    )
  end


  # desc "Deploy a new version to the Google Play"
  # lane :deploy do
  #   gradle(task: "clean assembleRelease")
  #   upload_to_play_store
  # end
end
